version: "3"

services:
  database:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/data/db
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: poll

volumes:
  pg-data:
    driver: local